apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: m3f1ilr3l-python-gitops
  description: This is GitOps manifest for m3f1ilr3l-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=m3f1ilr3l-python
    backstage.io/kubernetes-id: m3f1ilr3l-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: m3f1ilr3l-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:m3f1ilr3l-python
